# version: '3.8'

services:
  # crm app (PHP-FPM)
  crm-app:
    env_file:
      - .env  # This loads variables from .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_ENV='${APP_ENV}'
    container_name: crm-app
    image: noumanlaravel/crm-app:latest   # <--- Add this
    volumes:
      # - .:/var/www/html  # Bind mount to sync your application code for local development only
      - laravel_storage:/var/www/html/storage  # Named volume for persistent data (e.g., Laravel storage)
      - laravel_logs:/var/www/html/storage/logs  # Named volume for logs
    networks:
      - crm-network
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db   # Ensure the app waits for db to start

    # MySQL database
  db:
    image: mysql:5.7
    container_name: crm-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}       # Create user with the specified username
      MYSQL_PASSWORD: ${DB_PASSWORD}   # Set password for the created user
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Allow empty password for root user in local
    networks:
      - crm-network
    ports:
      - 3307:3306

  # Nginx for reverse proxy
  nginx:
    image: nginx:alpine
    container_name: crm-nginx
    ports:
      - 8081:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - crm-app
    networks:
      - crm-network

  node:
    image: node:20
    container_name: crm-node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      NODE_ENV: "${APP_ENV}"
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge
volumes:
  laravel_storage: {}
  laravel_logs: {}